global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'legacy-system'
    static_configs:
      - targets: ['legacy-system:3200']
    scrape_interval: 10s
    
  - job_name: 'produit-service'
    static_configs:
      - targets: ['produit-service:3001']
    scrape_interval: 10s
    
  - job_name: 'stock-service'
    static_configs:
      - targets: ['stock-service:3002']
    scrape_interval: 10s
    
  - job_name: 'vente-service'
    static_configs:
      - targets: ['vente-service:3003']
    scrape_interval: 10s
    
  - job_name: 'reporting-service'
    static_configs:
      - targets: ['reporting-service:3004']
    scrape_interval: 10s
