{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Utilisation CPU (pourcentage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'erreurs 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(rate(http_requests_total{code=~\"500\"}[5m]) / rate(http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU des containers (pourcentage)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence moyenne globale (toutes routes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}